export const EQUIPMENT_ATTACHMET_SUCCESS = 'EQUIPMENT_ATTACHMET_SUCCESS';
export const EQUIPMENT_ATTACHMET_FAILURE = 'EQUIPMENT_ATTACHMET_FAILURE';
export const SAVE_EXISTING_EQUIPMENT_SUCCESS = 'SAVE_EXISTING_EQUIPMENT_SUCCESS';